# Generated by Django 3.1 on 2020-08-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200822_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='emp_id',
        ),
    ]
