# Generated by Django 3.1 on 2020-08-30 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200828_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='car_id',
        ),
    ]
