# Generated by Django 3.1 on 2020-09-02 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_inventory_is_diesel'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.BooleanField()),
                ('black', models.BooleanField()),
                ('blue', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.color'),
        ),
    ]
