# Generated by Django 3.1 on 2020-10-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='bumper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessory',
            name='car_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessory',
            name='car_mat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.color'),
        ),
    ]
