# Generated by Django 3.1 on 2020-10-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_inventory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='car_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory'),
        ),
    ]
