# Generated by Django 3.1 on 2020-10-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201004_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(default='', max_length=5),
        ),
    ]
