# Generated by Django 3.1 on 2020-10-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201006_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='discount',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='reg_fees',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='reg_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
