# Generated by Django 3.1 on 2020-10-06 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201006_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoiler', models.BooleanField(default=False)),
                ('bumper', models.BooleanField(default=False)),
                ('car_cover', models.BooleanField(default=False)),
                ('car_mat', models.BooleanField(default=False)),
                ('sale_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.sales')),
            ],
        ),
    ]
