# Generated by Django 3.1 on 2020-10-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_accessories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accessory',
        ),
    ]
