# Generated by Django 3.1 on 2020-10-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_accessory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='color',
        ),
        migrations.AddField(
            model_name='inventory',
            name='black',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='blue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='red',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='color',
        ),
    ]
