# Generated by Django 3.1 on 2020-10-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201006_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='car_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.inventory'),
        ),
    ]
